### ISSUE TITLE
 Working with a single cell

### ISSUE THREAD

**Issue by anarsitta** [future-architect/cheetah-grid#393]
Hello.
I was faced with the task, when I click on a cell, I need to display that it is clicked, but c-grid has no borders, so the standard selection will be useless.
When working with c-grid, is it possible to affect a single cell when it is selected?
Maybe it's possible to display the borders at the time of selection or change the background?
I tried various options, but it stood out at once the entire column or row.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
But, I still don't quite understand what you want to do. (Maybe it's because I don't know English very well.)
I think the selected cell is indicated by a border or something.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/16508807/221181272-eea971c2-c531-4082-967b-04c0545f563c.png">

What do you want to do?
Could you explain again what you want to do, using images etc.?

**Comment by anarsitta** [comment]
My table has no borders and no selection.
Maybe there's a way to highlight the background of a cell when it's selected, to show the user that it's selected.

**Comment by ota-meshi** [comment]
Are you using your own theme? If so there may be a problem with your implementation of it.
https://future-architect.github.io/cheetah-grid/documents/api/js/theme.html

Also, could you please share your source code for further investigation?

**Comment by anarsitta** [comment]
That's what I need. My problem is solved, I was extremely inattentive to the documentation. Thank you very much for the help!
